spring:
  datasource:
    url: jdbc:h2:mem:creditapp
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        webAllowOthers: false
  jpa:
    show-sql: true
    hibernate:
      properties:
        hibernate:
          format_sql: true
      ddl-auto: create-drop